# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://onibus.github.io/
title: 
email: onibus@no-reply
author: V'alkurm
description: > # "Write an awesome description for your new site here. 
  V'alkurm Emperor@Balmung
copyright: 'All rights reserved'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ValkurmTia
  - title: info
    url: https://wiki.ffxiv-roleplayers.com/pages/V%27alkurm_Emperor
